// <auto-generated />
namespace OCS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _03check : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03check));
        
        string IMigrationMetadata.Id
        {
            get { return "201708231039188_03-check"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
