// <auto-generated />
namespace OCS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _01InitialFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01InitialFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201708210826592_01-Initial-Fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
