// <auto-generated />
namespace OCS.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _02Ver001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02Ver001));
        
        string IMigrationMetadata.Id
        {
            get { return "201708220809038_02-Ver0.01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
